"$schema" = "./node_modules/wrangler/config-schema.json"
name = "bond-screener"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-05-21"
compatibility_flags = [ "nodejs_compat", "global_fetch_strictly_public" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true
